apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argocd
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
      argocd/app-namespace: default
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: guests
  lifecycle: experimental


